DEFAULT_ANDROID_SDK_ROOT = /opt/android/sdk
DEFAULT_ANDROID_NDK_ROOT = /opt/android/android-ndk-r20
DEFAULT_ANDROID_PLATFORM = android-21
DEFAULT_ANDROID_NDK_HOST = linux-x86_64
DEFAULT_ANDROID_ABIS = armeabi-v7a arm64-v8a x86 x86_64
ANDROID_JAVAC_TARGET_VERSION = 
ANDROID_JAVAC_SOURCE_VERSION = 
GCC_MACHINE_DUMP = 
